#!/usr/bin/env bash
echo "#!/usr/bin/env bash
sudo apt-get update -y && sudo apt-get upgrade -y > /var/log/update_script.log" > task
chmod +x ./task
sudo mv task /etc/cron.daily/
echo "0 4 * * 1 /etc/cron.daily/task" | sudo crontab
