#!/usr/bin/env bash
echo "#!/usr/bin/env bash
sudo apt-get update -y && sudo apt-get upgrade -y >> /var/log/update_script.log" > task
chmod 755 ./task
sudo mv task /etc/cron.daily/
echo "0 4 * * 1 root /etc/cron.daily/task" | crontab
